//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class EntryView
{
    [SerializeField]
    private UIDocument _document;
    public Image IconImg { get; private set; }

    public Label TipLable { get; private set; }

    public VisualElement MainRoot { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        IconImg = Root?.Q<Image>("IconImg");
        TipLable = Root?.Q<Label>("TipLable");
        MainRoot = Root?.Q<VisualElement>("MainRoot");
    }
}