//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class PokerGame
{
    [SerializeField]
    private UIDocument _document;
    public Image BasePokerValue { get; private set; }

    public VisualElement BasePoker { get; private set; }

    public VisualElement StockPanel { get; private set; }

    public VisualElement WastePanel { get; private set; }

    public VisualElement EmptyPanel { get; private set; }

    public VisualElement FoundationPanel_0 { get; private set; }

    public VisualElement FoundationPanel_1 { get; private set; }

    public VisualElement FoundationPanel_2 { get; private set; }

    public VisualElement FoundationPanel_3 { get; private set; }

    public VisualElement Tableau_0 { get; private set; }

    public VisualElement Tableau_1 { get; private set; }

    public VisualElement Tableau_2 { get; private set; }

    public VisualElement Tableau_3 { get; private set; }

    public VisualElement Tableau_4 { get; private set; }

    public VisualElement Tableau_5 { get; private set; }

    public VisualElement Tableau_6 { get; private set; }

    public VisualElement Bg { get; private set; }

    public VisualElement TopBox { get; private set; }

    public VisualElement BottomBox { get; private set; }

    public VisualElement MainRoot { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        BasePokerValue = Root?.Q<Image>("BasePokerValue");
        BasePoker = Root?.Q<VisualElement>("BasePoker");
        StockPanel = Root?.Q<VisualElement>("StockPanel");
        WastePanel = Root?.Q<VisualElement>("WastePanel");
        EmptyPanel = Root?.Q<VisualElement>("EmptyPanel");
        FoundationPanel_0 = Root?.Q<VisualElement>("FoundationPanel_0");
        FoundationPanel_1 = Root?.Q<VisualElement>("FoundationPanel_1");
        FoundationPanel_2 = Root?.Q<VisualElement>("FoundationPanel_2");
        FoundationPanel_3 = Root?.Q<VisualElement>("FoundationPanel_3");
        Tableau_0 = Root?.Q<VisualElement>("Tableau_0");
        Tableau_1 = Root?.Q<VisualElement>("Tableau_1");
        Tableau_2 = Root?.Q<VisualElement>("Tableau_2");
        Tableau_3 = Root?.Q<VisualElement>("Tableau_3");
        Tableau_4 = Root?.Q<VisualElement>("Tableau_4");
        Tableau_5 = Root?.Q<VisualElement>("Tableau_5");
        Tableau_6 = Root?.Q<VisualElement>("Tableau_6");
        Bg = Root?.Q<VisualElement>("Bg");
        TopBox = Root?.Q<VisualElement>("TopBox");
        BottomBox = Root?.Q<VisualElement>("BottomBox");
        MainRoot = Root?.Q<VisualElement>("MainRoot");
    }
}