//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class SelectModeView
{
    [SerializeField]
    private UIDocument _document;
    public Button OneCardBtn { get; private set; }

    public Button ThreeCardBtn { get; private set; }

    public VisualElement SelectBox { get; private set; }

    public VisualElement MainRoot { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        OneCardBtn = Root?.Q<Button>("OneCardBtn");
        ThreeCardBtn = Root?.Q<Button>("ThreeCardBtn");
        SelectBox = Root?.Q<VisualElement>("SelectBox");
        MainRoot = Root?.Q<VisualElement>("MainRoot");
    }
}