//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class WinView
{
    [SerializeField]
    private UIDocument _document;
    public Button NewGameBtn { get; private set; }

    public VisualElement FrameBox { get; private set; }

    public VisualElement MainRoot { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        NewGameBtn = Root?.Q<Button>("NewGameBtn");
        FrameBox = Root?.Q<VisualElement>("FrameBox");
        MainRoot = Root?.Q<VisualElement>("MainRoot");
    }
}